language: cpp

compiler:
  - clang
  
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

branches:
  except:
    - gh-pages

install:
  - make build

script:
  - make test

notifications:
  email: false
